### ISSUE TITLE
webserver gems are delay after boot

### ISSUE THREAD

**Issue by noha** [noha/virtual-gemstone#29]
monit is configured for a startup delay of 60 seconds. If we keep starting gems with monit there needs to be a more clever way of delaying when necessary

**Comment by mostalive** [comment]
What is the purpose of the delay? (Stephan and I tried to set the delays shorter in the monit configuration. did not seem to make that big a difference).

**Comment by noha** [comment]
Is the delay a show stopper? I personally think we can live with it for the time being

**Comment by mostalive** [comment]
it makes it extra slow to develop, so I'd prefer to be able to set it.
I don't know if it is useful to have the delay at all.

On Mon, 12 Mar 2012 13:23:57 -0700, Norbert Hartl
reply@reply.github.com
wrote:

> Is the delay a show stopper? I personally think we can live with it
> for the time being
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/29#issuecomment-4460823

## 

Willem van den Ende
Living Software is a partner in QWAN

**Comment by mostalive** [comment]
To be clear: it is configurable now 
(reposted here so others can read it too)
  chef.json.merge!({
       :monit => {
                :start_delay => "1" #wait just one second
        }
     })

Not sure why I wrote 'needs help'. Probably because I want to be able to configure it outside of the Vagrantfile, but per-user or jenkins job configuration can be a separate issue, as it affects more settings.

**Comment by noha** [comment]
Uh, my last comment was not included. I said that this issues is fixed because the delay is gone. If we have new requirements regarding configurability that should go in a new issue attached to another milestone
