### ISSUE TITLE
confirm versions in versions.txt to work on linux

### ISSUE THREAD

**Issue by noha** [noha/virtual-gemstone#40]
There is only Mac OS as working platform noted in versions.txt. A test is needed on linux to confirm it is also working there

**Comment by mostalive** [comment]
failing on linux at the moment.

**Comment by mostalive** [comment]
Succeeded with getting rvm to pick up my gems in jenkins, and bundler to go over that and install the gems (probably should use a separate gemset for each build, so that we can be sure it only uses what is defined in the bundle). Not sure what causes this:

Started by user anonymous
Building in workspace /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace
Checkout:workspace / /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace - hudson.remoting.LocalChannel@2986e62
Using strategy: Default
Last Built Revision: Revision f5c4b46aeef4465f92efc558f807ac431a29c1c1 (origin/master)
Checkout:workspace / /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace - hudson.remoting.LocalChannel@2986e62
Fetching changes from 1 remote Git repository
Fetching upstream changes from /home/willem/dev/spikes/virtual-gemstone
Commencing build of Revision f5c4b46aeef4465f92efc558f807ac431a29c1c1 (origin/master)
Checking out Revision f5c4b46aeef4465f92efc558f807ac431a29c1c1 (origin/master)
[workspace] $ /bin/bash /tmp/hudson5713643369096831015.sh
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
Using archive-tar-minitar (0.5.2) 
Using ffi (1.0.11) 
Using childprocess (0.3.1) 
Using erubis (2.7.0) 
Using i18n (0.6.0) 
Using json (1.5.4) 
Using log4r (1.1.10) 
Using net-ssh (2.2.2) 
Using net-scp (1.0.4) 
Using vagrant (1.0.1) 
Using bundler (1.1.0) 
[32mYour bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.[0m
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
/usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/vm.rb:44:in `to_s': wrong number of arguments(1 for 0) (ArgumentError)
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/vm.rb:44:in`forward_port'
    from /home/willem/.vagrant.d/boxes/gemstone-ubuntu11.10-ruby192-full/include/_Vagrantfile:10:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:83:in`call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:83:in `block (2 levels) in load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:79:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:79:in `block in load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:76:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/config/loader.rb:76:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:387:in`block in load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:417:in `[]'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:417:in`block in load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:408:in `map'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:408:in`load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/lib/vagrant/environment.rb:327:in `load!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.1/bin/vagrant:40:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/bin/vagrant:19:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/bin/vagrant:19:in`<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by mostalive** [comment]
With version 1.0.0 it seems to be an error in my Vagrantfile. Will look into this later. (modified my build script to run bundle exec vagrant up, so that it picks up vagrant from my bundle, as opposed to 1.0.1. that was still in the gemset)

Started by user anonymous
Building in workspace /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace
Checkout:workspace / /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace - hudson.remoting.LocalChannel@2986e62
Using strategy: Default
Last Built Revision: Revision 5d20a254700e240e6fb743c20f67dfcd8e0b7436 (origin/master)
Checkout:workspace / /home/willem/.hudson/jobs/vagrant gemstone incremental/workspace - hudson.remoting.LocalChannel@2986e62
Fetching changes from 1 remote Git repository
Fetching upstream changes from /home/willem/dev/spikes/virtual-gemstone
Commencing build of Revision 5d20a254700e240e6fb743c20f67dfcd8e0b7436 (origin/master)
Checking out Revision 5d20a254700e240e6fb743c20f67dfcd8e0b7436 (origin/master)
[workspace] $ /bin/bash /tmp/hudson6606039366332635875.sh
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
Using archive-tar-minitar (0.5.2) 
Using ffi (1.0.11) 
Using childprocess (0.3.1) 
Using erubis (2.7.0) 
Using i18n (0.6.0) 
Using json (1.5.4) 
Using log4r (1.1.10) 
Using net-ssh (2.2.2) 
Using net-scp (1.0.4) 
Using vagrant (1.0.0) 
Using bundler (1.1.0) 
[32mYour bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.[0m
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
Using /usr/local/rvm/gems/ruby-1.9.2-p290 with gemset virtual-gemstone
[default] VM not created. Moving on...
/usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/vm.rb:44:in `to_s': wrong number of arguments(1 for 0) (ArgumentError)
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/vm.rb:44:in`forward_port'
    from /home/willem/.vagrant.d/boxes/gemstone-ubuntu11.10-ruby192-full/include/_Vagrantfile:10:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:83:in`call'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:83:in `block (2 levels) in load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:79:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:79:in `block in load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:76:in`each'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/config/loader.rb:76:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:383:in`block in load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:413:in `[]'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:413:in`block in load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:404:in `map'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:404:in`load_config!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/lib/vagrant/environment.rb:323:in `load!'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/gems/vagrant-1.0.0/bin/vagrant:40:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/bin/vagrant:19:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p290@virtual-gemstone/bin/vagrant:19:in`<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by noha** [comment]
Hmmm, craig had the same problem. Your Vagrantfile needs an update. It is in the repo. Did you pull the new changes? The fix is removing the first argument (the "http",etc. strings) of the forward_port directive.
I tested it last night under a linux server and it worked right from the start

**Comment by mostalive** [comment]
are you sure you committed the Vagrantfile? I did a git fetch noha &&
git merge noha/master . that updated a bunch of things, but Vagrantfile
stayed the same. I'll do the modifications manually and see how that
goes.

On Tue, 13 Mar 2012 03:58:49 -0700, Norbert Hartl
reply@reply.github.com
wrote:

> Hmmm, craig had the same problem. Your Vagrantfile needs an update.
> It is in the repo. Did you pull the new changes? The fix is removing
> the first argument (the "http",etc. strings) of the forward_port
> directive.
> I tested it last night under a linux server and it worked right from
> the start
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/40#issuecomment-4471064

## 

Willem van den Ende
Living Software is a partner in QWAN

**Comment by mostalive** [comment]
Doublechecked, merge has worked - the string arguments have
disappeared.

still get the error to_s wrong number of arguments in forward_port.

these are the calls:
 if(vagrant_env.nil? || vagrant_env != "build")
    config.vm.forward_port(80,7778)
    config.vm.forward_port(50377, 50377)
    config.vm.forward_port(50378, 50378)
  end

I'll set the environment to 'build' and see if it does more.

cheers,

Willem

On Tue, 13 Mar 2012 03:58:49 -0700, Norbert Hartl
reply@reply.github.com
wrote:

> Hmmm, craig had the same problem. Your Vagrantfile needs an update.
> It is in the repo. Did you pull the new changes? The fix is removing
> the first argument (the "http",etc. strings) of the forward_port
> directive.
> I tested it last night under a linux server and it worked right from
> the start
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/noha/virtual-gemstone/issues/40#issuecomment-4471064

## 

Willem van den Ende
Living Software is a partner in QWAN

**Comment by noha** [comment]
I saw on the branch history that I first merged your pull request than I added the removal of the parameters and then I merged to whole stuff back to main. I tested it on two machines that a version vagrant > 1.0 likes the two parameter variant
